{
 "title": "Synack analyzer - kubernetes",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up, cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster\", generation=\"2\", kind=\"system\"}, node)"
    }
   },
   {
    "name": "threshold_synack_ms",
    "query": {
     "query": "label_values(synack_analyzer_info{cluster=~\"${cluster}\"},threshold_synack_ms)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "SynAck response time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SynAck respone $node",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "repeat": "node",
   "targets": [
    {
     "expr": "sum by (le) (rate(synack_analyzer_synack_response_time_ms_bucket{node=~\"$node\"}[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Long SynAcks responses rate (Threshold: $threshold_synack_ms ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "sum by (node) (rate(synack_analyzer_synack_longresponse_count{node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Long Synack responses ($threshold_synack_ms ms) within Time Range",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 114 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (delta(synack_analyzer_synack_longresponse_count{node=~\"$node\"}[$__range]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Internal Errors",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 120 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (synack_analyzer_errors{node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Syn count rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "- sum by (node) (rate(synack_analyzer_syn_count{node=~\"$node\", tag=\"vlan\"}[$__rate_interval]))  ",
     "legendFormat": "{{node}} vlan"
    },
    {
     "expr": "sum by (node) (rate(synack_analyzer_syn_count{node=~\"$node\", tag=\"non_vlan\"}[$__rate_interval]))",
     "legendFormat": "{{node}} non_vlan"
    }
   ]
  },
  {
   "title": "SynAck count rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "- sum by (node) (rate(synack_analyzer_synack_count{node=~\"$node\", tag=\"vlan\"}[$__rate_interval]))  ",
     "legendFormat": "{{node}} vlan"
    },
    {
     "expr": "sum by (node) (rate(synack_analyzer_synack_count{node=~\"$node\", tag=\"non_vlan\"}[$__rate_interval]))  ",
     "legendFormat": "{{node}} non_vlan"
    }
   ]
  },
  {
   "title": "Received (filtered) packets rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "sum by (node) (rate(synack_analyzer_stats_received_count{node=~\"$node\"}[1m]))",
     "legendFormat": "{{node}}"
    },
    {}
   ]
  },
  {
   "title": "Packet processing rate",
   "type": "timeseries",
   "description": "Packet processing rate in utility, how fast we can process filtered packets.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "targets": [
    {
     "expr": "sum by (node) (rate(synack_analyzer_filtered_processed_packet_count{node=~\"$node\"}[1m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Dropped packets rate -  no room",
   "type": "timeseries",
   "description": "Rate for Number of packets dropped because there was no room in the operating system's buffer when they arrived, because packets weren't being read fast enough.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "sum by (node) (rate(synack_analyzer_stats_dropped_count{node=~\"$node\"}[1m]))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Packets dropped by NIC or driver",
   "type": "timeseries",
   "description": "Number of packets dropped by the network interface or its driver.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "expr": "sum by (node) (synack_analyzer_stats_if_dropped_count{node=~\"$node\"})",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Internal Structure State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 146 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Internal Structure: Syn packets not processed yet $node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 147 },
   "repeat": "node",
   "targets": [
    {
     "expr": "sum by (node) (synack_core_syn_structure_items {node=~\"$node\", tag=\"vlan\"})",
     "legendFormat": "Items vlan"
    },
    {
     "expr": "sum by (node) (synack_core_syn_structure_capacity {node=~\"$node\", tag=\"vlan\"})",
     "legendFormat": "Capacity vlan"
    },
    {
     "expr": "sum by (node) (synack_core_syn_structure_items {node=~\"$node\", tag=\"non_vlan\"})",
     "legendFormat": "Items non_vlan"
    },
    {
     "expr": "sum by (node) (synack_core_syn_structure_capacity {node=~\"$node\", tag=\"non_vlan\"})",
     "legendFormat": "Capacity non_vlan"
    }
   ]
  },
  {
   "title": "SynAck analyzer consumption",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 259 },
   "targets": [
    {}
   ]
  },
  {
   "title": "MEM usage (Working Set)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum((container_memory_working_set_bytes{cluster=~\"$cluster\", pod=~\"synack-analyzer.*\", container!=\"\", container!=\"POD\"})) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "MEM usage (Resident)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{cluster=~\"$cluster\", pod=~\"synack-analyzer.*\"}  "
    }
   ]
  },
  {
   "title": "MEM usage (Virtua mem)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 260 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{cluster=~\"$cluster\", pod=~\"synack-analyzer.*\"}  "
    }
   ]
  },
  {
   "title": "Throttling",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 267 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_seconds_total{cluster=~\"$cluster\", pod=~\"synack-analyzer.*\", container!=\"\", container!=\"POD\", node=~\"$node\"}[1m])) by (node)",
     "legendFormat": "{{node}} {{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 267 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{cluster=~\"$cluster\", pod=~\"synack-analyzer.*\", container!=\"\", container!=\"POD\"}[1m])) by (node)",
     "legendFormat": "{{node}} {{pod}}"
    },
    {}
   ]
  }
 ]
}